name: Unit Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
    - 'main'

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - id: config_project
        name: Configure Project
        uses: threeal/cmake-action@v1.3.0
        with:
          source-dir: simulations
          build-dir: simulations/build

      - id: build_executables
        name: Build Simulation Executables
        run: cmake --build ${{ github.workspace }}/simulations/build

      - name: Run Simulation Unit Tests
        run: ${{ github.workspace }}/simulations/build/tests